export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_REQUEST_FAIL = 'SIGNIN_REQUEST_FAIL';
export const SIGNIN_REQUEST_SUCCESS = 'SIGNIN_REQUEST_SUCCESS';
export const LOGOUT = 'LOGOUT';
